### ISSUE TITLE
Enemies disappear 

### ISSUE THREAD

**Issue by antoiba86** [antoiba86/SaveTheBearGame#1]
When you minimize the Screen and you come back to the game, the enemies are disappeared. This issue maybe is a problem with the Garbage collector.

**Comment by jorgesumle** [comment]
*maybe is 
may be

**Comment by antoiba86** [comment]
Para nada.
May be a problem, puede ser un problema
Maybe is a problem, quizás es un problema

**Comment by antoiba86** [comment]
Issue solved. When you play, the stage is undecorated so you cannot minimize the game and the enemies don't dissapear.
